version: "3.9"

services:
  database:
    container_name: microservice_auth_database
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: microservice_auth_live
    ports:
      - "3401:3306"
    volumes:
      - "auth_local_mysql_data:/var/lib/mysql"
    networks:
      - microservices_network

  app:
    container_name: microservice_auth_service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      APP_ENV: local
      DATABASE_URL: mysql://root:password@database:3401/microservice_auth_live
      KAFKA_BROKER: host.docker.internal:9092
    ports:
      - "5001:3000"
    depends_on:
      - database
    volumes:
      - ./:/var/app/current
      - /var/app/current/node_modules
    networks:
      - microservices_network

networks:
  microservices_network:
    driver: bridge

volumes:
  auth_local_mysql_data: